version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tailortalk-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tailortalk-frontend
    ports:
      - "8501:8501"
    environment:
      # This tells the frontend how to reach the backend
      # 'backend' is the name of the service defined above
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
